///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace webTables
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the webTablesRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    [RepositoryFolder("155022b9-d62b-4e61-ab23-c188c3a757b6")]
    public partial class webTablesRepository : RepoGenBaseFolder
    {
        static webTablesRepository instance = new webTablesRepository();
        webTablesRepositoryFolders.AutomatedToolsTestSiteAppFolder _automatedtoolstestsite;

        /// <summary>
        /// Gets the singleton class instance representing the webTablesRepository element repository.
        /// </summary>
        [RepositoryFolder("155022b9-d62b-4e61-ab23-c188c3a757b6")]
        public static webTablesRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public webTablesRepository() 
            : base("webTablesRepository", "/", null, 0, false, "155022b9-d62b-4e61-ab23-c188c3a757b6", ".\\RepositoryImages\\webTablesRepository155022b9.rximgres")
        {
            _automatedtoolstestsite = new webTablesRepositoryFolders.AutomatedToolsTestSiteAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("155022b9-d62b-4e61-ab23-c188c3a757b6")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The AutomatedToolsTestSite folder.
        /// </summary>
        [RepositoryFolder("c5b3d5fc-84d5-408a-92fd-e4cf05f03ea6")]
        public virtual webTablesRepositoryFolders.AutomatedToolsTestSiteAppFolder AutomatedToolsTestSite
        {
            get { return _automatedtoolstestsite; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    public partial class webTablesRepositoryFolders
    {
        /// <summary>
        /// The AutomatedToolsTestSiteAppFolder folder.
        /// </summary>
        [RepositoryFolder("c5b3d5fc-84d5-408a-92fd-e4cf05f03ea6")]
        public partial class AutomatedToolsTestSiteAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _htmltableInfo;

            /// <summary>
            /// Creates a new AutomatedToolsTestSite  folder.
            /// </summary>
            public AutomatedToolsTestSiteAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AutomatedToolsTestSite", "/dom[@domain='www.edgewordstraining.co.uk']", parentFolder, 30000, null, false, "c5b3d5fc-84d5-408a-92fd-e4cf05f03ea6", "")
            {
                _htmltableInfo = new RepoItemInfo(this, "HtmlTable", ".//div[#'right-column']/table[1]", 30000, null, "f9f86b19-b844-4626-b687-91653ee7839d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c5b3d5fc-84d5-408a-92fd-e4cf05f03ea6")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c5b3d5fc-84d5-408a-92fd-e4cf05f03ea6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The HtmlTable item.
            /// </summary>
            [RepositoryItem("f9f86b19-b844-4626-b687-91653ee7839d")]
            public virtual Ranorex.TableTag HtmlTable
            {
                get
                {
                    return _htmltableInfo.CreateAdapter<Ranorex.TableTag>(true);
                }
            }

            /// <summary>
            /// The HtmlTable item info.
            /// </summary>
            [RepositoryItemInfo("f9f86b19-b844-4626-b687-91653ee7839d")]
            public virtual RepoItemInfo HtmlTableInfo
            {
                get
                {
                    return _htmltableInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}